#!/bin/bash 

# at least remove world writable permissions

usage="

  Usage: $( basename ${0} ) [-U] [paths...]

  Remove world-writable permissions from paths.
  Paths can be specified as arguments or passed in via stdin.

  It does not recurse; though it will discriminate sticky-bits and symlinks.

"

# expect piped input from stdin or a specified file
if [[ ! -p /dev/stdin && $# -eq 0 ]]
then

  cmd_name="$( basename ${0} )"

  echo -ne "\nEgg: We found no input!\n\nTry:\n shell> ${cmd_name} <path>\nor\n shell> echo \"file list\" | ${cmd_name}\n\n" >&2
  exit 1

fi

OPTIND=
while getopts 'Uh' flag
do
 case "${flag}" in
  h) echo "${usage}"; exit 0;;
 esac
 shift $(( ${OPTIND} - 1 ))
 OPTIND=
done



IFS=$'\n'
while read -r path
do

    # just remove world-writable permission
    # if path exists and is not a symlink or has the sticky bit set
    if [[ -e "${path}" && ( ! -L "${path}" && -k "${path}" ]]
    then
      chmod -c o-w ${path}
    fi

done <<<"${*:-$(</dev/stdin)}"
IFS=' \t\n'
