#!/bin/bash 

# function to remove temp files
function clnup(){
  [[ -f "${ifile}" ]]    && rm "${ifile}"
  [[ -f "${ifileblr}" ]] && rm "${ifileblr}"
}

# run clnup if we receive any of the following signals
trap clnup HUP INT TERM KILL

# define / create tempfile
ifile="$(mktemp).png"
ifileblr="${ifile}.blurred"

# screengrab
scrot -zq 50 "${ifile}"

# get current screen resolution
geom=$( xrandr --current | sed -ne '1s/.*current \([0-9]\+\) x \([0-9]\+\).*/\1x\2/ p' )

# apply gaussian filter to the screen grab and save in temp file
convert -filter Gaussian \
        -define filter:sigma=9 \
        -resize "${geom}" -extent "${geom}" \
        -gravity center \
        -background black \
        "${ifile}" "${ifileblr}"

# run i3lock with the blurred image
i3lock -i "${ifileblr}" -e -c 000000 

# having returned from i3lock, run cleanup
clnup
